on:
  push:
    branches: [main]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ['backend', 'frontend'] }
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        # working-directory: frontend
        run: npm ci
  build:
    name: Build and Deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install Railway
        # working-directory: frontend
        run: npm i -g @railway/cli
      - name: Deploy
        # working-directory: frontend
        run: railway up
        env:
          RAILWAY_TOKEN: ${{secrets.RAILWAY_TOKEN}}
